
DROP TABLE IF EXISTS m_user;

CREATE TABLE m_user (
 id BIGINT NOT NULL,
 name VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

ALTER TABLE m_user ADD CONSTRAINT PK_m_user PRIMARY KEY (id);
